const fs = require('fs');
const { execSync } = require('child_process');

// NOTE: This script is intended to be run with `npx license-checker --production --json` piped to stdin.
// Example: npx license-checker --production --json | node scripts/license-update.js

console.log('Generating license file...');

try {
  const jsonInput = fs.readFileSync(0, 'utf-8'); // Read from stdin
  const data = JSON.parse(jsonInput);

  const header = `This file is automatically generated by 'npm run update:license'.
Do not edit this file manually.

This file contains the licenses for the libraries used in this project.

`;

  const out = Object.keys(data).map(key => {
    const pkg = data[key];
    let licenseContent = pkg.licenseText || '(License text not found.)';

    // Fallback to reading the license file if licenseText is missing or too short
    if ((!pkg.licenseText || pkg.licenseText.length < 20) && pkg.licenseFile && fs.existsSync(pkg.licenseFile)) {
      licenseContent = fs.readFileSync(pkg.licenseFile, 'utf-8');
    }

    return [
      '================================================================================',
      '',
      `Package: ${key}`,
      `License: ${pkg.licenses}`,
      `Repository: ${pkg.repository}`,
      '',
      licenseContent
    ].join('\n');
  }).join('\n\n');

  fs.writeFileSync('public/licenses.txt', header + out);
  console.log('Successfully updated public/licenses.txt');

} catch (error) {
  console.error('Failed to generate license file. Is the JSON from license-checker being piped correctly?');
  console.error(error);
  process.exit(1);
}
