import StyleSheet from '../../app/styles/StyleSheet';
import { CSSProperties } from 'react';
import { BOARD_COLS } from './core';

export const styles: { [key: string]: CSSProperties } = StyleSheet.create({
  gameArea: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '100%',
    maxHeight: '100vh',
  },
  board: {
    display: 'grid',
    gridTemplateColumns: `repeat(${BOARD_COLS}, 1fr)`,
    gap: '5px',
    backgroundColor: '#4b5563',
    padding: '5px',
    borderRadius: '0.5rem',
    width: '100%',
    maxWidth: 'min(70vh, 80vw)',
    flexGrow: 1,
    minHeight: 0,
    aspectRatio: '3 / 4',
  },
  cell: {
    width: '100%',
    height: '100%',
    backgroundColor: '#e5e7eb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.875rem',
    fontWeight: 'bold',
    borderRadius: '0.375rem',
    border: '1px solid #9ca3af',
    position: 'relative',
  },
  selectedCell: {
    backgroundColor: '#bfdbfe',
  },
  validMoveCell: {
    backgroundColor: '#dcfce7',
  },
  validDropCell: {
    backgroundColor: '#fef9c3',
  },
  capturableCell: {
    backgroundColor: '#bae6fd',
  },
  threatenedCell: {
    boxShadow: 'inset 0 0 0 4px #fca5a5',
  },
  selectableCellHighlight: {
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
  },
  capturedPiecesBox: {
    width: '100%',
    maxWidth: 'min(70vh, 80vw)',
    padding: '0.5rem',
    borderRadius: '0.5rem',
    backgroundColor: '#ffffff',
    boxSizing: 'border-box',
    flexShrink: 0,
    margin: '0.5rem 0',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  capturedPiecesTitle: {
    fontSize: '1rem',
    fontWeight: 'bold',
    writingMode: 'vertical-rl',
    textOrientation: 'mixed',
    paddingRight: '0.5rem',
    margin: 0,
    color: '#4b5563',
  },
  capturedPiecesList: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '0.5rem',
    flexWrap: 'nowrap',
    overflowX: 'auto',
    flexGrow: 1,
    minHeight: '50px',
  },
  capturedPiece: {
    width: '45px',
    height: '45px',
    padding: 0,
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '0.25rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  selectedCapturedPiece: {
    backgroundColor: '#bfdbfe',
    boxShadow: '0 0 0 2px #3b82f6',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '0.5rem',
    textAlign: 'center',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  modalTitle: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    marginBottom: '1rem',
  },
  modalText: {
    fontSize: '1.125rem',
    marginBottom: '1.5rem',
  },
  modalButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: '#3b82f6',
    color: 'white',
    borderRadius: '0.25rem',
    border: 'none',
    cursor: 'pointer',
    fontSize: '1rem',
  },
  moveIndicator: {
    position: 'absolute',
    width: '14px',
    height: '14px',
    pointerEvents: 'none',
    filter: 'drop-shadow(0 0 1px rgba(0, 0, 0, 0.7))',
  },
  indicatorN: {
    clipPath: 'polygon(50% 0%, 0% 100%, 100% 100%)',
    top: '3px', left: '50%', transform: 'translateX(-50%)',
  },
  indicatorNE: {
    clipPath: 'polygon(0% 0%, 100% 0%, 100% 100%)',
    top: '3px', right: '3px',
  },
  indicatorE: {
    clipPath: 'polygon(0% 0%, 100% 50%, 0% 100%)',
    top: '50%', right: '3px', transform: 'translateY(-50%)',
  },
  indicatorSE: {
    clipPath: 'polygon(0% 100%, 100% 100%, 100% 0%)',
    bottom: '3px', right: '3px',
  },
  indicatorS: {
    clipPath: 'polygon(0% 0%, 100% 0%, 50% 100%)',
    bottom: '3px', left: '50%', transform: 'translateX(-50%)',
  },
  indicatorSW: {
    clipPath: 'polygon(0% 0%, 0% 100%, 100% 100%)',
    bottom: '3px', left: '3px',
  },
  indicatorW: {
    clipPath: 'polygon(0% 50%, 100% 0%, 100% 100%)',
    top: '50%', left: '3px', transform: 'translateY(-50%)',
  },
  indicatorNW: {
    clipPath: 'polygon(0% 0%, 100% 0%, 0% 100%)',
    top: '3px', left: '3px',
  },
});
